spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ""
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect