spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ""
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS SCOTT;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

basic-auths:
  - user: allen
    password: password
    roles:
      - READ
      - WRITE