apiVersion: v1
kind: Service
metadata:
  name: employee-service-app-v1
  namespace: restful-services
  labels:
    app: employee-service-app
    version: v1
spec:
  ports:
    - port: 80
      name: http
      targetPort: ui-port
  clusterIP: None
  selector:
    app: employee-service-app
    version: v1